one:
	g++ -std=c++11 -I/opt/X11/include -o myfilter tbb_myfilter1.cpp -L/opt/X11/lib -lX11 -ljpeg -ltbb

two:
	g++ -std=c++11 -I/opt/X11/include -o myfilter tbb_myfilter2.cpp -L/opt/X11/lib -lX11 -ljpeg -ltbb

three:
	g++ -std=c++11 -I/opt/X11/include -o myfilter tbb_myfilter3.cpp -L/opt/X11/lib -lX11 -ljpeg -ltbb